version: "3"
services:
  retailchain-app:
    image: retailchain-app
    ports:
      - "8080:8080"
    networks:
      - retailchain-network
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - retailchain-network
    environment:
      - MYSQL_ROOT_PASSWORD=Sm1234
      - MYSQL_DATABASE=retail  

networks:
  retailchain-network: